### PR TITLE
Fix building process with test

### PR DESCRIPTION
**Pull request by Theosakamg**
For start testing only on test command. (#3)

Actually, when you launch build command. the test is run in all command (see https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks )
prefer to use `assemble` gradle task to `build`.

### CODE REVIEW

**Comment by Theosakamg** [comment]
Linked to #2

**Comment by esteve** [comment]
Thanks! The problem with using `assemble` is that it's not available on the Android plugin for Gradle. I think the most flexible way would be to write a Gradle plugin that checks which one is available and act accordingly. What do you think?

**Comment by Theosakamg** [comment]
@esteve `assemble` is a gradle Task for java and android.
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Tasks
http://stackoverflow.com/questions/4597850/gradle-build-without-tests

But I'am ok for Gradle plugin

**Comment by esteve** [comment]
@Theosakamg I thought I had tried using `assemble`, let me try it again with Android and maybe we won't need a Gradle plugin for now.

**Comment by Theosakamg** [comment]
I check on external android project :

```
./gradlew assemble
:Application:preBuild UP-TO-DATE
:Application:preDebugBuild UP-TO-DATE
:Application:checkDebugManifest
:Application:preReleaseBuild UP-TO-DATE
...
:Application:packageRelease
:Application:assembleRelease
:Application:assemble

BUILD SUCCESSFUL
```

And on ROS2 Android WS :

```
Process package 'ros2_listener_android' with context:
--------------------------------------------------------------------------------
 source_space => /home/micky/ros-workspace/ros2java/ros2_android_ws/src/ros2_java/ros2_android_examples/ros2_listener_android
  build_space => /home/micky/ros-workspace/ros2java/ros2_android_ws/build_isolated/ros2_listener_android
install_space => /home/micky/ros-workspace/ros2java/ros2_android_ws/install_isolated/ros2_listener_android
   make_flags => -j4, -l4
  build_tests => False
--------------------------------------------------------------------------------
+++ Building 'ros2_listener_android'
==> '/usr/bin/gradle -Pament.build_space=...  -Pament.build_tests=False -Pament.android_stl=gnustl_shared -Pament.android_abi=armeabi-v7a -Pament.android_ndk=/opt/android/android-ndk-r12b assemble' in '/home/micky/ros-workspace/ros2java/ros2_android_ws/src/ros2_java/ros2_android_examples/ros2_listener_android'
Incremental java compilation is an incubating feature.
:cleanNativeLibs UP-TO-DATE
:copyNativeLibs
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript
:generateDebugBuildConfig
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:compileDebugJavaWithJavac
None of the classes needs to be compiled! Analysis took 0.052 secs. 
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:prePackageMarkerForDebug
:transformClassesWithDexForDebug
Merged dex #1 (2 defs/2,2KiB)
Merged dex #2 (12 defs/8,2KiB)
Merged dex #3 (9 defs/9,1KiB)
Merged dex #4 (7 defs/7,6KiB)
Merged dex #5 (1 defs/1,2KiB)
Merged dex #6 (13 defs/7,3KiB)
Result is 44 defs/39,3KiB. Took 0,1s
:mergeDebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript
:generateReleaseBuildConfig
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources UP-TO-DATE
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:compileReleaseJavaWithJavac
None of the classes needs to be compiled! Analysis took 0.004 secs. 
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease
:prePackageMarkerForRelease
:transformClassesWithDexForRelease
Merged dex #1 (2 defs/2,2KiB)
Merged dex #2 (9 defs/9,1KiB)
Merged dex #3 (7 defs/7,6KiB)
Merged dex #4 (12 defs/8,1KiB)
Merged dex #5 (1 defs/1,2KiB)
Merged dex #6 (13 defs/7,3KiB)
Result is 44 defs/39,1KiB. Took 0,0s
:mergeReleaseJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForRelease
:processReleaseJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForRelease
:packageRelease
:assembleRelease
:assemble
:deployArtifacts

BUILD SUCCESSFUL
```

From clean workspace, and worked on device.

**Comment by esteve** [comment]
I've made some changes to your branch and merged it, see https://github.com/esteve/ament_java/pull/4

Thanks!

**Pull request closed without merging**
